language: minimal

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/

stages:
  - lint
  - release-ff
  - auto

jobs:
  include:
    - stage: lint
      name: "Lint the Helm chart"
      script:
        - make
        - make lint
    - stage: release-ff
      name: "Push commits to current release branch"
      if: type = push AND branch =~ /^master$/
      script:
        - make
        - make release-ff
    - stage: auto
      name: "Auto trigger mch-repo"
      if: type = push AND branch =~ /^master$/
      script: 
        - git clone --single-branch --branch master https://${MCH_REPO_BOT_TOKEN}@github.com/stolostron/multicloudhub-repo.git
        - cd multicloudhub-repo
        - ./cicd-scripts/chartAutomation.sh console-chart
